# Generated by Django 4.1.5 on 2023-02-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('quartier', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=30)),
                ('lettreMotivation', models.FileField(blank=True, upload_to='document')),
                ('releverDeNote', models.FileField(blank=True, upload_to='document')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('Autre', 'Autre')], max_length=32)),
                ('naissance', models.DateTimeField(verbose_name='date de naisssance')),
                ('nationnalite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntiteRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGroupe.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Conseiller_orientation',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appGroupe.personne')),
                ('grade', models.CharField(choices=[('li', 'licence'), ('ma', 'Master'), ('do', 'Docteorat')], max_length=20)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGroupe.adresse')),
            ],
            bases=('appGroupe.personne',),
        ),
        migrations.CreateModel(
            name='Bachelier',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appGroupe.personne')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGroupe.adresse')),
                ('dossier', models.ManyToManyField(to='appGroupe.dossier')),
            ],
            bases=('appGroupe.personne',),
        ),
    ]
